name: DownloadSecureFile

on:
  workflow_call:
    outputs:
      secure_file:
        value: ${{ jobs.download_secure_file.outputs.file }}

    secrets:
       test:
        required: true
# env:
#   AZURE_KEYVAULT_NAME: 'kv-rtl-sma-prod'
#   AZURE_SECRET_NAME: 'keys'

jobs:
  download_secure_file:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.Download_Secrets.outputs.secure_file }}
#       output2: ${{ steps.step2.outputs.secondword }}
    steps:
    #  - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-2
     - name: Download_Secrets
       id: Download_Secrets
       run: |
         echo "secure_file=h${{ secrets.test }} | sed 's/./& /g'" >> $GITHUB_OUTPUT
         echo $GITHUB_OUTPUT
     - name: Set up secret file
       env:
         DEBUG_PASSWORD: ${{ secrets.test }}
       run: |

        # echo "value is $DEBUG_PASSWORD" | sed 's/./& /g' >> secrets.txt 
        echo "value is $DEBUG_PASSWORD" | sed 's/./& /g' >> $GITHUB_OUTPUT
        echo "secure_file=$DEBUG_PASSWORD" | sed 's/./& /g' >> $GITHUB_OUTPUT
#      - id: step2
#         run: echo "secondword=world" >> $GITHUB_OUTPUT
#     steps:
#       - name: Login to Azure
#         uses: Azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          
          
          
        
          
          
